packages:
  - "{alpine,angular,lit,nuxt,preact,react,solid,svelte,tanstack,vinext,vue}"
  - "{alpine,angular,lit,nuxt,preact,react,solid,svelte,tanstack,vinext,vue}/*"

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

catalog:
  "@module-federation/vite": "1.16.10"

minimumReleaseAgeExclude:
  - "@module-federation/dts-plugin@2.6.0"
  - "@module-federation/error-codes@2.6.0"
  - "@module-federation/managers@2.6.0"
  - "@module-federation/runtime-core@2.6.0"
  - "@module-federation/runtime@2.6.0"
  - "@module-federation/sdk@2.6.0"
  - "@module-federation/third-party-dts-extractor@2.6.0"
